export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS';

export const LOGIN_INITIALIZE = 'LOGIN_INITIALIZE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_INITIALIZE = 'SIGNUP_INITIALIZE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SOCIALLOGIN_INITIALIZE = 'SOCIALLOGIN_INITIALIZE';
export const SOCIALLOGIN_SUCCESS = 'SOCIALLOGIN_SUCCESS';
export const SOCIALLOGIN_ERROR = 'SOCIALLOGIN_ERROR';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const USER_PROFILE_INITIALIZE = 'USER_PROFILE_INITIALIZE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

export const ADD_CARD_ERROR = 'ADD_CARD_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_CREDIT_CARD_SUCCESS = 'GET_CREDIT_CARD_SUCCESS';

export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';

export const GOOGLEOAUTHLOAD = 'GOOGLEOAUTHLOAD';
export const FBOAUTHLOAD = 'FBOAUTHLOAD';

export const UNAUTHORIZATIONACTION = 'UNAUTHORIZATIONACTION';

export const GET_USER_NOTIFICATION_SUCCESS = 'GET_USER_NOTIFICATION_SUCCESS';

export const PASSWORD_UPDATE_ERROR = 'PASSWORD_UPDATE_ERROR';

export const NOTIFICATION_UPDATE_ERROR = 'NOTIFICATION_UPDATE_ERROR';

export const EMAIL_UPDATE_SUCCESS = 'EMAIL_UPDATE_SUCCESS';
export const EMAIL_UPDATE_ERROR = 'EMAIL_UPDATE_ERROR';

export const GTAG_UNKNOWN_ID = 'GTAG_UNKNOWN_ID';
