export const TIMEKIT_MODAL_HANDLER = 'TIMEKIT_MODAL_HANDLER';
export const INITIALIZE_TIMEKIT_WIDGET = 'INITIALIZE_TIMEKIT_WIDGET';
export const HANDLE_TIMEKIT_WIDGET = 'HANDLE_TIMEKIT_WIDGET';

export const LOADER_INCREMENT = 'LOADER_INCREMENT';
export const LOADER_DECREMENT = 'LOADER_DECREMENT';

export const PRODUCTS_PRICE_INITIALIZE = 'PRODUCTS_PRICE_INITIALIZE';
export const PRODUCTS_PRICE_SUCCESS = 'PRODUCTS_PRICE_SUCCESS';
export const PRODUCTS_PRICE_ERROR = 'PRODUCTS_PRICE_ERROR';

export const MANAGER_SPECIALIST_INITIALIZE = 'MANAGER_SPECIALIST_INITIALIZE';
export const MANAGER_SPECIALIST_SUCCESS = 'MANAGER_SPECIALIST_SUCCESS';
export const MANAGER_SPECIALIST_ERROR = 'MANAGER_SPECIALIST_ERROR';

export const THERAPIST_LISTING_INITIALIZE = 'THERAPIST_LISTING_INITIALIZE';
export const THERAPIST_LISTING_SUCCESS = 'THERAPIST_LISTING_SUCCESS';
export const THERAPIST_LISTING_ERROR = 'THERAPIST_LISTING_ERROR';

export const GET_REVIEWS_INITIALIZE = 'GET_REVIEWS_INITIALIZE';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const GET_PROJECT_PRICING_THERAPIST_INITIALIZE =
  'GET_PROJECT_PRICING_THERAPIST_INITIALIZE';
export const GET_PROJECT_PRICING_THERAPIST_SUCCESS =
  'GET_PROJECT_PRICING_THERAPIST_SUCCESS';
export const GET_PROJECT_PRICING_THERAPIST_ERROR =
  'GET_PROJECT_PRICING_THERAPIST_ERROR';

export const THERAPIST_PER_AVALIABILITY_INITIALIZE =
  'THERAPIST_PER_AVALIABILITY_INITIALIZE';
export const THERAPIST_PER_AVALIABILITY_SUCCESS =
  'THERAPIST_PER_AVALIABILITY_SUCCESS';
export const THERAPIST_PER_AVALIABILITY_ERROR =
  'THERAPIST_PER_AVALIABILITY_ERROR';

export const THERAPIST_PER_DATA_INITIALIZE = 'THERAPIST_PER_DATA_INITIALIZE';
export const THERAPIST_PER_DATA_SUCCESS = 'THERAPIST_PER_DATA_SUCCESS';
export const THERAPIST_PER_DATA_ERROR = 'THERAPIST_PER_DATA_ERROR';

export const GOOGLEMAP_INITIALIZE = 'GOOGLEMAP_INITIALIZE';

export const LAUNCHED_CITIES_SUCCESS = 'LAUNCHED_CITIES_SUCCESS';

export const BOOK_APPOINMENT_INITIALIZE = 'BOOK_APPOINMENT_INITIALIZE';
export const BOOK_APPOINMENT_SUCCESS = 'BOOK_APPOINMENT_SUCCESS';
export const BOOK_APPOINMENT_ERROR = 'BOOK_APPOINMENT_ERROR';

export const GET_BOOKING_DATA_INITIALIZE = 'GET_BOOKING_DATA_INITIALIZE';
export const GET_BOOKING_DATA_SUCCESS = 'GET_BOOKING_DATA_SUCCESS';
export const GET_BOOKING_DATA_ERROR = 'GET_BOOKING_DATA_ERROR';

export const ADD_BOOKING_TIP_INITIALIZE = 'ADD_BOOKING_TIP_INITIALIZE';
export const ADD_BOOKING_TIP_SUCCESS = 'ADD_BOOKING_TIP_SUCCESS';
export const ADD_BOOKING_TIP_ERROR = 'ADD_BOOKING_TIP_ERROR';

export const ADD_BOOKING_RECEIPT_INITIALIZE = 'ADD_BOOKING_RECEIPT_INITIALIZE';
export const ADD_BOOKING_RECEIPT_SUCCESS = 'ADD_BOOKING_RECEIPT_SUCCESS';
export const ADD_BOOKING_RECEIPT_ERROR = 'ADD_BOOKING_RECEIPT_ERROR';

export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';

export const BLOCK_THERAPIST_DATA = 'BLOCK_THERAPIST_DATA';

export const BOOKING_DETAIL_SUCCESS = 'BOOKING_DETAIL_SUCCESS';

export const INITIATE_MODIFY_BOOKING_SUCCESS =
  'INITIATE_MODIFY_BOOKING_SUCCESS';
export const INITIATE_MODIFY_BOOKING_ERROR = 'INITIATE_MODIFY_BOOKING_ERROR';

export const CANCLE_BOOKING_ERROR = 'CANCLE_BOOKING_ERROR';

export const GET_BOOKING_GUEST_SUCCESS = 'GET_BOOKING_GUEST_SUCCESS';
export const ADD_BOOKING_GUEST_ERROR = 'ADD_BOOKING_GUEST_ERROR';

export const GET_DISCOUNT_VALID_SUCCESS = 'GET_DISCOUNT_VALID_SUCCESS';

export const GET_REQUEST_DEMO_SUCCESS = 'GET_REQUEST_DEMO_SUCCESS';

export const REQUEST_DEMO_SUCCESS = 'REQUEST_DEMO_SUCCESS';
export const REQUEST_DEMO_ERROR = 'REQUEST_DEMO_ERROR';

export const GET_INTAKE_FORM_SUCCESS = 'GET_INTAKE_FORM_SUCCESS';

export const ADD_INTAKE_FORM_SUCCESS = 'ADD_INTAKE_FORM_SUCCESS';
export const ADD_INTAKE_FORM_ERROR = 'ADD_INTAKE_FORM_ERROR';
export const CLEAR_INTAKE_FORM_SUCCESS = 'CLEAR_INTAKE_FORM_SUCCESS';

export const ADD_COVID_FORM_SUCCESS = 'ADD_COVID_FORM_SUCCESS';
export const ADD_COVID_FORM_ERROR = 'ADD_COVID_FORM_ERROR';

export const GET_COVID_FORM_SUCCESS = 'GET_COVID_FORM_SUCCESS';

export const GET_INTAKE_FORM_DETAIL_SUCCESS = 'GET_INTAKE_FORM_DETAIL_SUCCESS';

export const GET_COVID_FORM_DETAIL_SUCCESS = 'GET_COVID_FORM_DETAIL_SUCCESS';

export const APP_CLEAR_ERROR = 'APP_CLEAR_ERROR';
